Base the defalt window screen and height off the desktop size.
RasmusD/StoryTime pull request #2
Opened 2019-03-17 04:26 UTC by mplooster

Seems useful if you want to have the window scale to the size of the desktop (which I don't know if you do or not).

2019-03-17 11:11 UTC, RasmusD requested changes
That is indeed not a bad idea. However on linux at least, due to the way windows snap they don't actually use the full screen real estate and this puts some of the sides beyond the window borders.
I suggest setting it to:

desktop.width * 0.95f and desktop.height * 0.95f

This will resolve the issue for now. There's a TODO to make screen resolution configurable and enable full screen etc. for the future.

But this was a good test to see if things are scaling right - which they seem t so far!

2019-03-24 23:47 UTC, mplooster commented
Sorry for the delay in updating this. I was trying my best to see if there was some way to account for the window snapping behavior, but I couldn't find anything quick and easy (seems like this is something SFML should handle for us, but it is what it is).

2019-03-25 10:42 UTC, RasmusD approved these changes

2019-03-25 10:43 UTC, RasmusD commented
No worries. No rush.

2019-03-25 10:43 UTC, merged